### ISSUE TITLE
有可能出错的情况

### ISSUE THREAD

**Issue by lazureice** [Taokyla/MikanToAria2#2]
您的这个程序很小巧，比 flexget 轻便多了。

不过我运气不好，第一次使用就遇到了一个问题。添加喵萌奶茶屋的rss： [古见同学](https://mikanani.me/RSS/Bangumi?bangumiId=2564&subgroupid=382) 。然后规则过滤1080简。

程序在发送第 3 集之后停止了。然而 `main.py` 中也没有限制每次 10 个。回到订阅源中，**发现这两个 item 的标题完全一样，因此判断后面的都已经下载过了**。
https://mikanani.me/Home/Episode/dcecd4086affeb7f3dfd7dab16b4ed8f0ded1c6b
https://mikanani.me/Home/Episode/63498dc8da812cfc3e1e7e3b79267c71542cae7f

可以看到标题完全一样。但是**地址不一样**。

不得不说，完全一样的标题很少见，我以前也没有遇见过。我猜测可能是做了什么改动，又重新上传了，而旧的也没有删。

1. 如果已经有同名再添加 rss，之前的集数全都不会发送给 aria2。
2. 如果是先添加 rss，再有同名，新版本就因同名而不发送。（当然，这种情况即使发送给 aria2，aria2 也会因为文件同名而停止下载。）这是aria2的问题，似乎也不好解决……

不过无论如何，毕竟它们是不同的资源，还是应该找一个办法区分比较好。aria2 的问题，归 aria2 去解决。

我觉得用 `<link>` 来辨别更好。
不用 `<guid>` 是因为蜜柑把 title 当作 guid，而不是像大多数情况把 link 当作 guid。当然蜜柑其实是对的，如果我们用正规的 rss 阅读器，就会在 guid 相同、但内容不同时更新内容，而不是直接退出。但这毕竟不是 rss 阅读器。

当然，不改也没事。这种情况真的很少遇到……我看了一下，就《古见同学》而言，蜜柑第 3 集有同名，而dmhy和萌番组都只有一个新版本。

**Comment by Taokyla** [comment]
title优先吧，最直观，改为每个url都会把所有话都尝试下载。
